src/main/java/com/gmail/kom/marijana/zadatak/beans/JsfBean.java
package com.gmail.kom.marijana.zadatak.beans;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

import org.springframework.beans.factory.annotation.Autowired;

import com.gmail.kom.marijana.zadatak.entities.Document;
import com.gmail.kom.marijana.zadatak.entities.DocumentItem;
import com.gmail.kom.marijana.zadatak.repositories.DocumentItemRepository;
import com.gmail.kom.marijana.zadatak.repositories.DocumentRepository;
import com.gmail.kom.marijana.zadatak.views.DocumentItemView;
import com.gmail.kom.marijana.zadatak.views.DocumentView;

@ManagedBean (name = "jsfBean", eager = true)
@RequestScoped
public class JsfBean {

	@Autowired
	private DocumentRepository docRepo;
	
	@Autowired
	private DocumentItemRepository docItemRepo;
	
	@ManagedProperty(value = "#{document}")
    private DocumentView document = new DocumentView();
	
	@ManagedProperty(value = "#{documentitem}")
    private DocumentItemView documentItem = new DocumentItemView();

    public void resetDocument(){
    	this.document.setId(0);
    	this.document.setName(null);
    	this.document.setDate(null);
    	this.document.setCode(null);
    }
	
    public void resetDocumentItem(){
    	this.documentItem.setId(0);
    	this.documentItem.setName(null);
    	this.documentItem.setPrice(null);
    	this.documentItem.setDocument(null);
    }
    
    public List<Document> getAllDocuments(){
    	return (List<Document>) docRepo.findAll();
    }
    
    public void viewDocument(Document doc) {
    	doc = docRepo.findOne(this.document.getId());
        
        this.document.setId(doc.getId());
        this.document.setName(doc.getName());
        this.document.setDate(doc.getDate());
        this.document.setCode(doc.getCode());
    }
    
    public String addNewDocument(){
    	Document doc = new Document();
    	
    	doc.setCode(this.document.getCode());
    	doc.setDate(this.document.getDate());
    	doc.setName(this.document.getName());
    	
    	docRepo.save(doc);
    	
    	return "documents.xhtml";
    }
    
    public String deleteDocument(Document doc) {
    	this.document.setId(doc.getId());
        
        docRepo.delete(doc);
    	
    	return "documents.xhtml";
    }
    
    public String editDocument() {
    	Document doc = new Document();
    	
    	doc.setId(this.document.getId());
    	doc.setCode(this.document.getCode());
    	doc.setDate(this.document.getDate());
    	doc.setName(this.document.getName());
    	
    	docRepo.save(doc);
    	
    	return "viewdocument.xhtml?faces-redirect=true&id=" + doc.getId();
    }
    
    public List<DocumentItem> getAllDocumentItems(){
    	Document doc = new Document();
    	
    	doc.setId(this.document.getId());
    	doc.setCode(this.document.getCode());
    	doc.setDate(this.document.getDate());
    	doc.setName(this.document.getName());
    	
    	return (List<DocumentItem>) docItemRepo.findByDocument(doc);
    }
    
    public void viewDocumentItem(){
    	DocumentItem docItem = docItemRepo.findOne(this.documentItem.getId());
        
        this.documentItem.setName(docItem.getName());
        this.documentItem.setPrice(docItem.getPrice());
        this.documentItem.setDocument(docItem.getDocument());
    }
    
    public String addNewDocumentItem(Document doc){
    	DocumentItem docItem = new DocumentItem();
    	
    	docItem.setName(this.documentItem.getName());
    	docItem.setPrice(this.documentItem.getPrice());
    	
    	doc = docRepo.findOne(this.document.getId());
    	docItem.setDocument(doc);
    	
    	docItemRepo.save(docItem);
    	
    	return "viewdocument.xhtml?faces-redirect=true&id=" + doc.getId();
    }
    
    public String deleteDocumentItem(DocumentItem docItem) {
    	
    	docItemRepo.delete(docItem);
    	
    	return "viewdocument.xhtml?faces-redirect=true&id=" + docItem.getDocument().getId();
    }
    
    public String editDocumentItem(){
    	DocumentItem docItem = new DocumentItem();
    	
    	docItem.setId(this.documentItem.getId());
    	docItem.setName(this.documentItem.getName());
    	docItem.setPrice(this.documentItem.getPrice());
    	docItem.setDocument(this.documentItem.getDocument());
    	
    	docItemRepo.save(docItem);
    	
    	return "viewdocument.xhtml?faces-redirect=true&id=" + docItem.getDocument().getId();
    }
    
    

	public DocumentItemView getDocumentItem() {
		return documentItem;
	}

	public void setDocumentItem(DocumentItemView documentItem) {
		this.documentItem = documentItem;
	}

	public DocumentRepository getDocRepo() {
		return docRepo;
	}

	public void setDocRepo(DocumentRepository docRepo) {
		this.docRepo = docRepo;
	}

	public DocumentItemRepository getDocItemRepo() {
		return docItemRepo;
	}

	public void setDocItemRepo(DocumentItemRepository docItemRepo) {
		this.docItemRepo = docItemRepo;
	}

	public DocumentView getDocument() {
		return document;
	}

	public void setDocument(DocumentView document) {
		this.document = document;
	}
}

src/main/java/com/gmail/kom/marijana/zadatak/entities/Document.java
package com.gmail.kom.marijana.zadatak.entities;


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

import com.fasterxml.jackson.annotation.JsonManagedReference;

@Entity
public class Document{

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private long id;
	
	private String code;
	
	private Date date;
	
	private String name;
	
	@JsonManagedReference
	@OneToMany (fetch=FetchType.EAGER,
			cascade=CascadeType.REMOVE,
			mappedBy="document")
	private List<DocumentItem> items = new ArrayList<>();
	
	public Document() {
		// TODO Auto-generated constructor stub
	}
	
	public Document(String code, Date date, String name) {
		super();
		this.code = code;
		this.date = date;
		this.name = name;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<DocumentItem> getItems() {
		return items;
	}

	public void setItems(List<DocumentItem> items) {
		this.items = items;
	}
	
	@Override
	public String toString() {
		return name;
	}
}

src/main/java/com/gmail/kom/marijana/zadatak/entities/DocumentItem.java
package com.gmail.kom.marijana.zadatak.entities;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import com.fasterxml.jackson.annotation.JsonBackReference;

@Entity
public class DocumentItem {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private long id;
	
	private String name;
	
	private Double price;
	
	@JsonBackReference
	@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name = "document_id")
	private Document document;
	
	public DocumentItem() {
		// TODO Auto-generated constructor stub
	}

	public DocumentItem(String name, Double price, Document document) {
		super();
		this.name = name;
		this.price = price;
		this.document = document;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Document getDocument() {
		return document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}
	
}

src/main/java/com/gmail/kom/marijana/zadatak/controller/ApiController.java
package com.gmail.kom.marijana.zadatak.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import com.gmail.kom.marijana.zadatak.entities.Document;
import com.gmail.kom.marijana.zadatak.entities.DocumentItem;
import com.gmail.kom.marijana.zadatak.repositories.DocumentItemRepository;
import com.gmail.kom.marijana.zadatak.repositories.DocumentRepository;

@RestController
@RequestMapping("/api")
public class ApiController {
	
	@Autowired
	private DocumentRepository documentRepo;
	
	@Autowired
	private DocumentItemRepository documentItemRepo;

	@GetMapping("/documents")
	public List<Document> getAllDocs(){
		return (List<Document>) documentRepo.findAll();
	}
	
	@GetMapping("/documents/{id}")
	public Document getDocument(@PathVariable long id){
	  return documentRepo.findOne(id);
	}
	
	@PostMapping("/documents/add")
	public Document addDocument(Document d){
	  return documentRepo.save(d);
	}
	
	@PostMapping("documents/delete/{id}")
	public void deleteDocument(@PathVariable long id){
		documentRepo.delete(id);
	}
	
	@PostMapping("/documents/update")
	public Document updateDocument(Document d){
	  return documentRepo.save(d);
	}
	
	@GetMapping("/documents/{id}/items")
	public List<DocumentItem> getAllItems(@PathVariable long id){
		Document doc = documentRepo.findOne(id);
		return doc.getItems();
	}
	
	@GetMapping("/documents/{id}/items/{item_id}")
	public DocumentItem getItem(@PathVariable long id, @PathVariable long item_id){
		return documentItemRepo.findOne(item_id);
	}
	
	@PostMapping("/documents/{id}/items/add")
	public DocumentItem addDocumentItem(@PathVariable long id, DocumentItem dItem){
		dItem.setDocument(documentRepo.findOne(id));
		return documentItemRepo.save(dItem);
	}
	
	@PostMapping("/documents/{id}/items/update")
	public DocumentItem updateDocumentItem(@PathVariable long id, DocumentItem dItem){
		dItem.setDocument(documentRepo.findOne(id));
		return documentItemRepo.save(dItem);
	}
	
	@PostMapping("/items/delete/{id}")
	public void deleteDocumentItem(@PathVariable long id){
		documentItemRepo.delete(id);
	}
}

src/main/webapp/documents.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<f:view>
	<ui:composition template="layout.xhtml">
		<ui:define name="content">
			<p:breadCrumb>
				<p:menuitem value="Documents" url="documents.jsf" />
			    <p:menuitem value="Documents" url="documents.jsf" />
			</p:breadCrumb>
			<br /><br />
			<p:fieldset legend="Documents">
				<h3 class="title ui-widget-header ui-corner-all"
					style="font-family: Arial, sans-serif; padding: 5px">List of
					documents</h3>
				<p:dataTable value="#{jsfBean.allDocuments}" var="document"
					border="1">
					<p:column>
						<f:facet name="header">
							<h:outputText value="ID" />
						</f:facet>
						<h:outputText value="#{document.id}" />
					</p:column>
					<p:column>
						<f:facet name="header">
							<h:outputText value="Name" />
						</f:facet>
						<p:link outcome="viewdocument.xhtml?id=#{document.id}"
							value="#{document.name}" />
					</p:column>
					<p:column>
						<f:facet name="header">
							<h:outputText value="Date" />
						</f:facet>
						<h:outputText value="#{document.date}">
							<f:convertDateTime pattern="dd. MMM yyyy." />
						</h:outputText>
					</p:column>
					<p:column>
						<f:facet name="header">
							<h:outputText value="Code" />
						</f:facet>
						<h:outputText value="#{document.code}" />
					</p:column>
					<p:column>
						<h:form>
							<p:commandButton value="Delete"
								actionListener="#{jsfBean.deleteDocument(document)}"
								type="submit" update="@form" ajax="false" />
						</h:form>
					</p:column>
				</p:dataTable>
				<br />
				<p:button outcome="newdocument.xhtml" value="Add New Document" />
			</p:fieldset>
		</ui:define>
	</ui:composition>
</f:view>
</html>

src/main/webapp/edititem.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<f:view>
	<ui:composition template="layout.xhtml">
		<f:metadata>
			<f:viewParam name="id" value="#{jsfBean.documentItem.id}" />
			<f:viewAction action="#{jsfBean.viewDocumentItem}" />
		</f:metadata>
		<ui:define name="title">Document item</ui:define>
		<ui:define name="content">
		<p:breadCrumb>
			<p:menuitem value="Documents" url="documents.jsf" />
			<p:menuitem value="Documents" url="documents.jsf" />
			<p:menuitem value="#{jsfBean.documentItem.document.name}"
				url="viewdocument.jsf?id=#{jsfBean.documentItem.document.id}" />
			<p:menuitem value="#{jsfBean.documentItem.name}"
				url="edititem.jsf?id=#{jsfBean.documentItem.id}" />
		</p:breadCrumb>
		<br /><br />
			<p:fieldset legend="Document item information">
				<h:form id="editItemForm" prependId="false">
					<p:panelGrid columns="2" border="0" layout="grid"
						style="margin: 20px;">
						<p:outputLabel value="Name : " />
						<h:inputText value="#{jsfBean.documentItem.name}" />
						<p:outputLabel value="Price :" />
						<h:inputText value="#{jsfBean.documentItem.price}" />
					</p:panelGrid>
					<p:commandButton value="Edit document item" update="name,price" action="#{jsfBean.editDocumentItem}"
						styleClass="ui-priority-primary" type="submit" ajax="false" />
				</h:form>
			</p:fieldset>
		</ui:define>
	</ui:composition>
</f:view>
</html>

src/main/webapp/layout.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<f:view>
    <h:head>
        <title><ui:insert name="title">Application</ui:insert></title>
    </h:head>
    <h:body>
    	<div class="ui-grid ui-grid-responsive">
            <div class="ui-grid-row">
                <div class="ui-grid-col-2"></div>
                <div class="ui-grid-col-8">
                    <p:growl for="errors" showDetail="true" autoUpdate="true"/>
                    <ui:insert name="content">Default content</ui:insert>
                </div>
                <div class="ui-grid-col-2"></div>
            </div>
        </div>
        <br/><br/>
    </h:body>
</f:view>
</html>

src/main/webapp/newdocument.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<f:view>
	<ui:composition template="layout.xhtml">
		<f:metadata>
			<f:viewAction action="#{jsfBean.resetDocument}" />
		</f:metadata>
		<ui:define name="title">New document</ui:define>
		<ui:define name="content">
		<p:breadCrumb>
			<p:menuitem value="Documents" url="documents.jsf" />
			<p:menuitem value="Documents" url="documents.jsf" />
			<p:menuitem value="Add new document" url="newdocument.jsf" />
		</p:breadCrumb>
		<br /><br />
			<h:form id="newDocForm" prependId="false">
				<p:panelGrid columns="2">
					<p:outputLabel value="Document name : " />
					<h:inputText value="#{jsfBean.document.name}" />
					<p:outputLabel value="Code :" />
					<h:inputText value="#{jsfBean.document.code}" />
					<p:outputLabel value="Date :" />
					<p:calendar value="#{jsfBean.document.date}"
						pattern="dd. MMM yyyy." />
				</p:panelGrid>
				<br />
				<p:commandButton value="Add New Document"
					action="#{jsfBean.addNewDocument}" type="submit" update="@form"
					ajax="false" />
			</h:form>
		</ui:define>
	</ui:composition>
</f:view>
</html>

src/main/webapp/newdocumentitem.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<f:view>
	<ui:composition template="layout.xhtml">
		<f:metadata>
			<f:viewAction action="#{jsfBean.resetDocumentItem}" />
		</f:metadata>
		<ui:define name="title">New document item</ui:define>
		<ui:define name="content">
		<p:breadCrumb>
			<p:menuitem value="Documents" url="documents.jsf" />
			<p:menuitem value="Documents" url="documents.jsf" />
			<p:menuitem value="#{jsfBean.document.name}"
				url="viewdocument.jsf?id=#{jsfBean.document.id}" />
			<p:menuitem value="Add new item" url="newdocumentitem.jsf" />
		</p:breadCrumb>
		<br /><br />
			<p:fieldset legend="Document Item">
				<h3 class="title ui-widget-header ui-corner-all"
					style="font-family: Arial, sans-serif; padding: 5px">Create
					new item</h3>
				<h:form id="newItemForm" prependId="false">
					<p:panelGrid columns="2">
						<p:outputLabel value="Item name : " />
						<h:inputText value="#{jsfBean.documentItem.name}" />
						<p:outputLabel value="Price :" />
						<h:inputText value="#{jsfBean.documentItem.price}" />
					</p:panelGrid>
					<br />
					<p:commandButton value="Add New Item"
						action="#{jsfBean.addNewDocumentItem(document)}" />
				</h:form>
			</p:fieldset>
		</ui:define>
	</ui:composition>
</f:view>
</html>

src/main/webapp/viewdocument.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<f:view>
	<ui:composition template="layout.xhtml">
		<f:metadata>
			<f:viewParam name="id" value="#{jsfBean.document.id}" />
			<f:viewAction action="#{jsfBean.viewDocument(document)}" />
		</f:metadata>
		<ui:define name="title">Document</ui:define>
		<ui:define name="content">
		<p:breadCrumb>
			<p:menuitem value="Documents" url="documents.jsf" />
			<p:menuitem value="Documents" url="documents.jsf" />
			<p:menuitem value="#{jsfBean.document.name}" url="viewdocument.jsf?id=#{jsfBean.document.id}" />
		</p:breadCrumb>
		<br /><br />
			<p:fieldset legend="Document information">
				<h:form id="documentForm" prependId="false">
					<p:panelGrid columns="2" border="0" layout="grid"
						style="margin: 20px;">
						<p:outputLabel value="Document name : " />
						<h:inputText value="#{jsfBean.document.name}" />
						<p:outputLabel value="Code :" />
						<h:inputText value="#{jsfBean.document.code}" />
						<p:outputLabel value="Date :" />
						<p:calendar value="#{jsfBean.document.date}"
							pattern="dd. MMM yyyy." />
					</p:panelGrid>
					<p:commandButton value="Edit document" update="name,code,date"
						action="#{jsfBean.editDocument}" styleClass="ui-priority-primary"
						type="submit" ajax="false" />
				</h:form>
			</p:fieldset>
			<h3 class="title ui-widget-header ui-corner-all"
				style="font-family: Arial, sans-serif; padding: 5px">List of
				document items</h3>
			<p:dataTable value="#{jsfBean.allDocumentItems}" var="documentItem">
				<p:column>
					<f:facet name="header">
						<h:outputText value="ID" />
					</f:facet>
					<h:outputText value="#{documentItem.id}" />
				</p:column>
				<p:column>
					<f:facet name="header">
						<h:outputText value="Name" />
					</f:facet>
					<p:link outcome="edititem.xhtml?id=#{documentItem.id}"
						value="#{documentItem.name}" />
				</p:column>
				<p:column>
					<f:facet name="header">
						<h:outputText value="Price" />
					</f:facet>
					<h:outputText value="#{documentItem.price}" />
				</p:column>
				<p:column>
					<h:form>
						<p:commandButton value="Delete"
							action="#{jsfBean.deleteDocumentItem(documentItem)}"
							type="submit" update="@form" ajax="false" />
					</h:form>
				</p:column>
			</p:dataTable>
			<br />
			<p:button outcome="newdocumentitem.xhtml"
				value="Add New Document Item" />
		</ui:define>
	</ui:composition>
</f:view>
</html>